- 20-unhint-small-dejavu-lgc-sans.conf
- 20-unhint-small-dejavu-lgc-sans-mono.conf
- 20-unhint-small-dejavu-lgc-serif.conf
- 20-unhint-small-dejavu-sans.conf
- 20-unhint-small-dejavu-sans-mono.conf
- 20-unhint-small-dejavu-serif.conf
- 30-metric-aliases.conf
- 30-opensymbol.conf
- 40-nonlatin.conf
- 45-generic.conf
- 45-Hack.conf
- 45-latin.conf
- 48-spacing.conf
- 49-sansserif.conf
- 50-user.conf
- 51-local.conf
- 57-dejavu-sans.conf
- 57-dejavu-sans-mono.conf
- 57-dejavu-serif.conf
- 58-dejavu-lgc-sans.conf
- 58-dejavu-lgc-sans-mono.conf
- 58-dejavu-lgc-serif.conf
- 60-generic.conf
- 60-latin.conf
- 61-urw-bookman.conf
- 61-urw-c059.conf
- 61-urw-d050000l.conf
- 61-urw-fallback-backwards.conf
- 61-urw-fallback-generics.conf
- 61-urw-gothic.conf
- 61-urw-nimbus-mono-ps.conf
- 61-urw-nimbus-roman.conf
- 61-urw-nimbus-sans.conf
- 61-urw-p052.conf
- 61-urw-standard-symbols-ps.conf
- 61-urw-z003.conf
- 65-fonts-lmodern.conf
- 65-fonts-persian.conf
- 65-nonlatin.conf
- 69-unifont.conf
- 70-fonts-noto-cjk.conf
- 80-delicious.conf
- 90-synthetic.conf
