{{ if not (env "CHEZMOI_IGNORE_ALL_OF_THE_EXTERNALS") }}
# Vim plugin manager
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# Our default GTK and Openbox themes:
# Greylooks, GreylooksGreen, GreylooksHuman and GreylooksOk
{{ range .miscGreylooksThemes }}
[".local/share/themes/{{ . }}"]
    type = "archive"
    url = "https://github.com/vbrand1984/greylooks/archive/master.zip"
    format = "zip"
    exact = true
    stripComponents = 2
    include = ["greylooks-master/{{ . }}/**"]
    refreshPeriod = "168h"
{{ end }}


### Fonts ###

# JetBrainsMonoNL and InconsolataLGC fonts
[".local/share/fonts/nerd-fonts"]
    type = "archive"
    url = "https://drive.google.com/uc?export=download&id=1v9Wldc35JyORC_IADhoTyCM3R1n009bB"
    format = "tar.zst"
    stripComponents = 1
    exact = true
    include = ["nerd-fonts/*.ttf"]
    refreshPeriod = "168h"

# MS fonts
[".local/share/fonts/winfonts"]
    type = "archive"
    url = "https://drive.google.com/uc?export=download&id=1oqMz4-otLnuu3IgenYV5_IqJ7Mzc0kbh"
    format = "tar.zst"
    stripComponents = 1
    exact = true
    include = ["winfonts/*.tt?"]
    refreshPeriod = "168h"


### Distro-specific ###

{{ if .sysIsDebBased }}
# In Debian-based distros, we need to install obmenu-generator externally
[{{ joinPath (.dirDownloadedScripts | trimPrefix .chezmoi.homeDir | trimPrefix "/") .apps.debiansObmenuGeneratorName | quote }}]
    type= "file"
    url = "https://raw.githubusercontent.com/trizen/obmenu-generator/master/obmenu-generator"
    refreshPeriod = "168h"
    executable = false
    readonly = true
    private = true
{{ end }}

{{ if and .sysIsDebianBased (not .sysHasSystemd) }}
# Pipewire-launcher script from Gentoo to be installed and used in Devuan
[{{ joinPath (.dirDownloadedScripts | trimPrefix .chezmoi.homeDir | trimPrefix "/") .apps.devuansPipewireLauncher | quote }}]
    type= "file"
    url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/media-video/pipewire/files/gentoo-pipewire-launcher.in-r3"
    filter.command = "sed"
    filter.args = [ "s/@GENTOO_PORTAGE_EPREFIX@//g" ]
    refreshPeriod = "168h"
    executable = false
    readonly = true
    private = true
{{ end }}


### Personal ###

{{/* if and .sysIsBrandsPrivate .sysIsDesktopRig */}}
# Font with weather icons which is used in my python-powered conky weather widget
# Only used on my desktop rig
[".local/share/fonts/weathericons-regular-webfont.ttf"]
    type = "file"
    url = "https://github.com/erikflowers/weather-icons/raw/master/font/weathericons-regular-webfont.ttf"
    refreshPeriod = "168h"
{{/* end */}}

{{ end }}
