---
# {{{ .app: Various applications settings

app:
  envIgnoreExternals: 'CHEZMOI_IGNORE_ALL_OF_THE_EXTERNALS'

  defaultTmuxSessionName: 'A'

  # This thing is used in commands like notify-send and dunstify,
  # when ``--action`` parameter is used.
  # This delimiter separates action tag from action text,
  # and in dunstify, it's ``,``, whereas in notify-send, it's ``=``
  # See take-screenshot-x.sh script
  notifierActionDelimiter:
    dunstify: ','
    notify-send: '='

# }}}
# {{{ .cmd: Various commands

cmd:

  # Default editor to use.
  # That's the value for $EDITOR and $VISUAL environment variables
  editor: '/usr/bin/vim'

  # Start audio mixer from status bar and with keyboard shortcut
  audioMixer: 'pavucontrol-qt --tab=3'

  # Wayland-specific desktop commands
  wayland:

    # Contol sound volume
    volumeUp: 'swayosd-client --output-volume +2'
    volumeDown: 'swayosd-client --output-volume -2'
    volumeMute: 'swayosd-client --output-volume mute-toggle'

    # Lock the screen
    lockScreen: 'swaylock'

    # Logout dialogue
    logout: 'wlogout --buttons-per-row=2'

# }}}
# {{{ .file: Filenames

file:
  defaultWallpaper: 'Heracles-2500x1406.jpeg'

  ansible:
    config: 'ansible.cfg'
    inventory: 'inventory.yml'
    localPlaybook: 'local-chezmoi-playbook.yml'

  # https://pkginfo.devuan.org/cgi-bin/policy-query.html??c=package&q=devuan-keyring
  devuanKeyring:
    pattern: 'devuan-keyring_%s_all.deb'
    current: excalibur

    # https://pkginfo.devuan.org/cgi-bin/package-query.html?c=package&q=devuan-keyring=2025.08.09
    excalibur:
      ver: '2025.08.09'
      sha256: '1d87328cb485c96ee5c9eca06bba05159183099a4c6df6121052fc1047cf594f'
      size: 196336

    # https://pkginfo.devuan.org/cgi-bin/package-query.html?c=package&q=devuan-keyring=2026.01.13
    freia:
      ver: '2026.01.13'
      sha256: 'c53429b645bea3a6edd427d70b7fb49b629a99fc9b9915260026a300540400f2'
      size: 199160

  graphite:

    # 
    gtk:
      pattern: 'Graphite-gtk-theme-%s.tar.gz'
      ver: '2026-08-23'

    # https://github.com/vinceliuice/Graphite-gtk-theme
    kde:
      pattern: 'Graphite-kde-theme-%s.tar.gz'
      ver: '2026-08-22'

  # For deb-based distros:
  papirusFolders:
    pattern: 'papirus-folders-%s.tar.gz'
    ver: '1.14.0'
    sha512: 'f66592828052080c40a73f76f1d26d32cbbee895061d299aa32490668457aa702c4d21d689c04b241623072cf6d2da41e4db757dd6db1a107deb046e91c8c9f3'
    size: 10513

# }}}
# {{{ .message: Various messages

message:

  managedByChezmoi: 'This file is managed by chezmoi template:'
  dumbShebang: 'Run this script as following:'
  farewell: 'Vero a sessione exire vis?'

# }}}
# {{{ .misc: Miscellaneous settings

misc:

  greylooksThemes:
    - Greylooks
    - GreylooksGreen
    - GreylooksHuman
    - GreylooksOk
    - GreylooksPurple
    - GreylooksSand

# }}}
# {{{ .tmpl: Paths to templates
tmpl:

  chromiumFlags: 'chromium-flags.yaml.tmpl'

  listFileHashes: 'list-file-hashes.tmpl'

  wlogoutLayout: 'wlogout-layout.yaml.tmpl'

  gtkSettingsIni: 'gtk-settings.ini.tmpl'

  # Openbox-related stuff
  ob:
    # Absolute path to the obmenu-generator script
    # Used in obmenu-generator's schema.pl and in Openbox' menu.xml
    obmenuGeneratorPath: 'openbox/obmenuGeneratorPath.tmpl'

    # Default rc.xml for Openbox to be used in the modify script for it
    defaultOpenboxRc: 'openbox/defaultOpenboxRc.xml.tmpl'

  # Messages to be printed in files or on the screen
  msg:
    managedByChezmoi: 'msg-managed-by-chezmoi.tmpl'
    printRunningScriptName: 'scripts-shell/print-running-script-name.sh.tmpl'

  # Palettes for various applications
  palette:
    conky: 'palettes/conky.toml'
    terminal: 'palettes/terminal.yaml.tmpl'
    tint2: 'palettes/tint2.yaml.tmpl'
    wlogout: 'palettes/wlogout.yaml.tmpl'

  # Package lists for installing
  pkgLists:
    clipitBuildDeps: 'pkglists/clipitBuildDeps.yaml.tmpl'
    preInstall: 'pkglists/preInstall.yaml.tmpl'

  # Shell scripts
  sh:
    funcEnsureSudoIsWorking: 'scripts-shell/ensure-sudo-is-working.sh.tmpl'
    funcPrintMessage: 'scripts-shell/print-message.sh.tmpl'
    funcPkgManager: 'scripts-shell/pkg-manager.sh.tmpl'

  # Shebangs, mostly dumb
  shebang:
    dumbSh: 'shebangs/dumb-sh.tmpl'

  # Various commands
  shellCmd:
    openboxLogout: 'shell-cmd/openbox-logout.tmpl'
    obmenuGenerator: 'shell-cmd/obmenu-generator.tmpl'

# }}}
...
