---

- name: Prepare system fontconfig configuration
  get_fontconfig_config_symlinks_list:
    conf_avail: "{{ vbd_sys_conf_fc_cfg.conf_avail }}"
    conf_d: "{{ vbd_sys_conf_fc_cfg.conf_d }}"
    conf_needed: "{{ vbd_sys_conf_fc_cfg.conf_needed }}"
    antialias: "{{ vbd_sys_conf_fc_cfg.antialias }}"
    autohint: "{{ vbd_sys_conf_fc_cfg.autohint }}"
    autohint_if_no_hinting: "{{ vbd_sys_conf_fc_cfg.autohint_if_no_hinting }}"
    hinting: "{{ vbd_sys_conf_fc_cfg.hinting }}"
    hintstyle: "{{ vbd_sys_conf_fc_cfg.hintstyle }}"
    lcdfilter: "{{ vbd_sys_conf_fc_cfg.lcdfilter }}"
    rgba: "{{ vbd_sys_conf_fc_cfg.rgba }}"
    bitmaps: "{{ vbd_sys_conf_fc_cfg.bitmaps }}"
    scale_bitmap_fonts: "{{ vbd_sys_conf_fc_cfg.scale_bitmap_fonts }}"
  register: vbd_sys_conf_fc_cfg_symlinks_list
  tags: [files, system_files, fontconfig]

- name: Adjust system fontconfig configuration
  become: true
  ansible.builtin.file:
    src: "{{ item.src if 'src' in item else '' }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    owner: "{{ 'root' if item.state == 'link' else '' }}"
    group: "{{ 'root' if item.state == 'link' else '' }}"
    follow: false
    mode: ""
  loop: "{{ vbd_sys_conf_fc_cfg_symlinks_list.file_list }}"
  tags: [files, system_files, fontconfig]

...
