---

directories:
  - '.cache'
  - '.config/gtk-3.0'
  - '.config/mc'
  - '.local/share'
  - '.local/state'
  - '.vim/autoload'

symlinks:
  - '.config/gtk-3.0/settings.ini'
  - '.vim/vimrc'

remove:
  - '.viminfo'
  - '.vimrc'

...
