---

directories:
  - '.vim/autoload'
  - '.config/gtk-3.0'
  - '.config/mc'
  - '.local/share'
  - '.local/state'

symlinks:
  - '.vim/vimrc'
  - '.config/gtk-3.0/settings.ini'

remove:
  - '.vimrc'
  - '.viminfo'

...
